[default]
# admin emails
admin_users = ['admin01@example.com']

# for flask
secret_key = '<replace-with-your-key>'

# sendinblue
SIB_API_KEY = "<replace-with-your-key>"

# gmail
GMAIL_EMAIL_HOST = 'smtp.gmail.com'
GMAIL_EMAIL_PORT = 465
GMAIL_EMAIL_HOST_USER = '<replace-with-your-key>'
GMAIL_EMAIL_HOST_PASSWORD = '<replace-with-your-key>'

# mailtrap
MAILTRAP_EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
MAILTRAP_EMAIL_PORT = '2525'
MAILTRAP_EMAIL_HOST_USER = '<replace-with-your-key>'
MAILTRAP_EMAIL_HOST_PASSWORD = '<replace-with-your-key>'